server:
  port: 8761

eureka:
  instance:
    hostname: server1
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://server2:8762/eureka,http://server3:8763/eureka