server:
  port: 8762

eureka:
  instance:
    hostname: server2
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka,http://server3:8763/eureka